package com.ecommerce.product.application.service;

import com.ecommerce.common.exception.BusinessException;
import com.ecommerce.common.exception.EntityNotFoundException;
import com.ecommerce.common.exception.ErrorCode;
import com.ecommerce.product.domain.model.Brand;
import com.ecommerce.product.domain.repository.BrandRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class BrandServiceTest {

    @Mock
    private BrandRepository brandRepository;

    @InjectMocks
    private BrandService brandService;

    @Test
    void create_shouldSaveBrandWithAutoGeneratedSlug() {
        given(brandRepository.existsByName("Iron Heart")).willReturn(false);
        given(brandRepository.existsBySlug("iron-heart")).willReturn(false);
        given(brandRepository.save(any(Brand.class))).willAnswer(inv -> inv.getArgument(0));

        Brand result = brandService.create("Iron Heart", null, "JP", "WORKWEAR", 1975, "Premium denim", null);

        assertThat(result.getName()).isEqualTo("Iron Heart");
        assertThat(result.getSlug()).isEqualTo("iron-heart");
        verify(brandRepository).save(any(Brand.class));
    }

    @Test
    void create_shouldSaveBrandWithProvidedSlug() {
        given(brandRepository.existsByName("Iron Heart")).willReturn(false);
        given(brandRepository.existsBySlug("ih-denim")).willReturn(false);
        given(brandRepository.save(any(Brand.class))).willAnswer(inv -> inv.getArgument(0));

        Brand result = brandService.create("Iron Heart", "ih-denim", "JP", "WORKWEAR", 1975, null, null);

        assertThat(result.getSlug()).isEqualTo("ih-denim");
    }

    @Test
    void create_shouldThrowWhenNameAlreadyExists() {
        given(brandRepository.existsByName("Iron Heart")).willReturn(true);

        assertThatThrownBy(() -> brandService.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));

        verify(brandRepository, never()).save(any());
    }

    @Test
    void create_shouldThrowWhenSlugAlreadyExists() {
        given(brandRepository.existsByName("Iron Heart")).willReturn(false);
        given(brandRepository.existsBySlug("iron-heart")).willReturn(true);

        assertThatThrownBy(() -> brandService.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));

        verify(brandRepository, never()).save(any());
    }

    @Test
    void findBySlug_shouldReturnBrandWhenExists() {
        Brand brand = Brand.create("Red Wing", null, "US", "AMERICANA", 1905, null, null);
        given(brandRepository.findBySlug("red-wing")).willReturn(Optional.of(brand));

        Brand result = brandService.findBySlug("red-wing");

        assertThat(result.getName()).isEqualTo("Red Wing");
    }

    @Test
    void findBySlug_shouldThrowWhenNotFound() {
        given(brandRepository.findBySlug(anyString())).willReturn(Optional.empty());

        assertThatThrownBy(() -> brandService.findBySlug("unknown"))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void findAll_shouldReturnAllBrands() {
        List<Brand> brands = List.of(
                Brand.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null),
                Brand.create("Red Wing", null, "US", "AMERICANA", 1905, null, null)
        );
        given(brandRepository.findAll()).willReturn(brands);

        List<Brand> result = brandService.findAll();

        assertThat(result).hasSize(2);
    }

    @Test
    void update_shouldUpdateBrandFields() {
        Brand brand = Brand.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null);
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(brandRepository.existsByName("Iron Heart Updated")).willReturn(false);
        given(brandRepository.existsBySlug("iron-heart-updated")).willReturn(false);
        given(brandRepository.save(any(Brand.class))).willAnswer(inv -> inv.getArgument(0));

        Brand result = brandService.update(1L, "Iron Heart Updated", "iron-heart-updated",
                "JP", "WORKWEAR", 1975, "Updated description", null);

        assertThat(result.getName()).isEqualTo("Iron Heart Updated");
        assertThat(result.getSlug()).isEqualTo("iron-heart-updated");
        assertThat(result.getDescription()).isEqualTo("Updated description");
    }

    @Test
    void update_shouldThrowWhenBrandNotFound() {
        given(brandRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> brandService.update(99L, "Name", null, null, null, null, null, null))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void update_shouldThrowWhenNewNameConflictsWithOtherBrand() {
        Brand brand = Brand.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null);
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(brandRepository.existsByName("Red Wing")).willReturn(true);

        assertThatThrownBy(() -> brandService.update(1L, "Red Wing", null, "US", "AMERICANA", 1905, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));
    }

    @Test
    void update_shouldThrowWhenNewSlugConflictsWithOtherBrand() {
        Brand brand = Brand.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null);
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(brandRepository.existsByName("Iron Heart New")).willReturn(false);
        given(brandRepository.existsBySlug("red-wing")).willReturn(true);

        assertThatThrownBy(() -> brandService.update(1L, "Iron Heart New", "red-wing", "JP", "WORKWEAR", 1975, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));
    }

    @Test
    void delete_shouldRemoveBrand() {
        Brand brand = Brand.create("Carhartt", null, "US", "WORKWEAR", 1889, null, null);
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));

        brandService.delete(1L);

        verify(brandRepository).delete(brand);
    }

    @Test
    void delete_shouldThrowWhenBrandNotFound() {
        given(brandRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> brandService.delete(99L))
                .isInstanceOf(EntityNotFoundException.class);
    }
}
