package com.ecommerce.product.application.service;

import com.ecommerce.common.exception.BusinessException;
import com.ecommerce.common.exception.EntityNotFoundException;
import com.ecommerce.common.exception.ErrorCode;
import com.ecommerce.product.api.dto.request.ProductSearchRequest;
import com.ecommerce.product.domain.model.Brand;
import com.ecommerce.product.domain.model.Product;
import com.ecommerce.product.domain.model.ProductImage;
import com.ecommerce.product.domain.model.ProductTranslation;
import com.ecommerce.product.domain.model.ProductVariant;
import com.ecommerce.product.domain.repository.BrandRepository;
import com.ecommerce.product.domain.repository.ProductImageRepository;
import com.ecommerce.product.domain.repository.ProductRepository;
import com.ecommerce.product.domain.repository.ProductTranslationRepository;
import com.ecommerce.product.domain.repository.ProductVariantRepository;
import com.ecommerce.product.infra.persistence.ProductQueryRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;

    @Mock
    private ProductVariantRepository productVariantRepository;

    @Mock
    private ProductTranslationRepository productTranslationRepository;

    @Mock
    private ProductImageRepository productImageRepository;

    @Mock
    private BrandRepository brandRepository;

    @Mock
    private ProductQueryRepository productQueryRepository;

    @InjectMocks
    private ProductService productService;

    private Brand createBrand() {
        return Brand.create("Iron Heart", null, "JP", "WORKWEAR", 1975, null, null);
    }

    private Product createProduct(Brand brand) {
        return Product.create(brand, "iron-heart-21oz-selvedge", "DENIM", null,
                new BigDecimal("350.0000"), "USD", null, null, null,
                new BigDecimal("21.0"), "DENIM", "SELVEDGE");
    }

    @Test
    void create_shouldSaveProductWithAutoGeneratedSlug() {
        Brand brand = createBrand();
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(productRepository.existsBySlug("iron-heart-21oz-selvedge-denim")).willReturn(false);
        given(productRepository.save(any(Product.class))).willAnswer(inv -> inv.getArgument(0));

        Product result = productService.create(1L, null, "DENIM", null,
                new BigDecimal("350.0000"), "USD", null, null, null,
                new BigDecimal("21.0"), "DENIM", "SELVEDGE", "21oz Selvedge Denim");

        assertThat(result.getSlug()).isEqualTo("iron-heart-21oz-selvedge-denim");
        verify(productRepository).save(any(Product.class));
    }

    @Test
    void create_shouldSaveProductWithProvidedSlug() {
        Brand brand = createBrand();
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(productRepository.existsBySlug("custom-slug")).willReturn(false);
        given(productRepository.save(any(Product.class))).willAnswer(inv -> inv.getArgument(0));

        Product result = productService.create(1L, "custom-slug", "DENIM", null,
                new BigDecimal("350.0000"), "USD", null, null, null, null, null, null, "Test Product");

        assertThat(result.getSlug()).isEqualTo("custom-slug");
    }

    @Test
    void create_shouldThrowWhenBrandNotFound() {
        given(brandRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> productService.create(99L, null, "DENIM", null,
                new BigDecimal("350.0000"), "USD", null, null, null, null, null, null, "Test"))
                .isInstanceOf(EntityNotFoundException.class);

        verify(productRepository, never()).save(any());
    }

    @Test
    void create_shouldThrowWhenSlugAlreadyExists() {
        Brand brand = createBrand();
        given(brandRepository.findById(1L)).willReturn(Optional.of(brand));
        given(productRepository.existsBySlug("iron-heart-test")).willReturn(true);

        assertThatThrownBy(() -> productService.create(1L, "iron-heart-test", "DENIM", null,
                new BigDecimal("350.0000"), "USD", null, null, null, null, null, null, "Test"))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));

        verify(productRepository, never()).save(any());
    }

    @Test
    void findByPublicId_shouldReturnProductWhenExists() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findByPublicId("SOME_PUBLIC_ID")).willReturn(Optional.of(product));

        Product result = productService.findByPublicId("SOME_PUBLIC_ID");

        assertThat(result.getSlug()).isEqualTo("iron-heart-21oz-selvedge");
    }

    @Test
    void findByPublicId_shouldThrowWhenNotFound() {
        given(productRepository.findByPublicId(anyString())).willReturn(Optional.empty());

        assertThatThrownBy(() -> productService.findByPublicId("NONEXISTENT"))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void search_shouldDelegateToQueryRepository() {
        ProductSearchRequest request = new ProductSearchRequest(
                null, "DENIM", null, null, null, null, null, 0, 20, "createdAt", "desc");
        Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20), 0);
        given(productQueryRepository.search(any(), any())).willReturn(page);

        Page<Product> result = productService.search(request);

        assertThat(result).isNotNull();
        verify(productQueryRepository).search(any(), any());
    }

    @Test
    void searchByKeyword_shouldDelegateToRepository() {
        Page<Product> page = new PageImpl<>(List.of(), PageRequest.of(0, 20), 0);
        given(productRepository.searchByKeyword(eq("denim"), any())).willReturn(page);

        Page<Product> result = productService.searchByKeyword("denim", 0, 20);

        assertThat(result).isNotNull();
        verify(productRepository).searchByKeyword(eq("denim"), any());
    }

    @Test
    void update_shouldUpdateProductFields() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productRepository.save(any(Product.class))).willAnswer(inv -> inv.getArgument(0));

        Product result = productService.update(1L, null, "OUTERWEAR", "1940s_MILITARY",
                new BigDecimal("500.0000"), "USD", null, null, null, null, "WOOL", "HERRINGBONE");

        assertThat(result.getCategory()).isEqualTo("OUTERWEAR");
        assertThat(result.getEra()).isEqualTo("1940s_MILITARY");
    }

    @Test
    void update_shouldThrowWhenProductNotFound() {
        given(productRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> productService.update(99L, null, "DENIM", null,
                new BigDecimal("350"), "USD", null, null, null, null, null, null))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void update_shouldThrowWhenNewSlugConflicts() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productRepository.existsBySlug("existing-slug")).willReturn(true);

        assertThatThrownBy(() -> productService.update(1L, "existing-slug", "DENIM", null,
                new BigDecimal("350"), "USD", null, null, null, null, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));
    }

    @Test
    void delete_shouldRemoveProduct() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));

        productService.delete(1L);

        verify(productRepository).delete(product);
    }

    @Test
    void delete_shouldThrowWhenProductNotFound() {
        given(productRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> productService.delete(99L))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void addVariant_shouldSaveVariant() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productVariantRepository.existsBySku("IH-634S-32")).willReturn(false);
        given(productVariantRepository.save(any(ProductVariant.class))).willAnswer(inv -> inv.getArgument(0));

        ProductVariant result = productService.addVariant(1L, "IH-634S-32", "32",
                "Indigo", "#1a237e", null, null,
                new BigDecimal("54.0"), null, null, null, null, null, null, null);

        assertThat(result.getSku()).isEqualTo("IH-634S-32");
        verify(productVariantRepository).save(any(ProductVariant.class));
    }

    @Test
    void addVariant_shouldThrowWhenSkuAlreadyExists() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productVariantRepository.existsBySku("EXISTING-SKU")).willReturn(true);

        assertThatThrownBy(() -> productService.addVariant(1L, "EXISTING-SKU", "32",
                null, null, null, null, null, null, null, null, null, null, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));

        verify(productVariantRepository, never()).save(any());
    }

    @Test
    void addVariant_shouldThrowWhenProductNotFound() {
        given(productRepository.findById(99L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> productService.addVariant(99L, "SKU-1", "M",
                null, null, null, null, null, null, null, null, null, null, null, null))
                .isInstanceOf(EntityNotFoundException.class);
    }

    @Test
    void updateVariant_shouldUpdateFields() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        ProductVariant variant = ProductVariant.create(product, "OLD-SKU", "32",
                null, null, null, null, null, null, null, null, null, null, null, null);
        given(productRepository.existsById(1L)).willReturn(true);
        given(productVariantRepository.findById(10L)).willReturn(Optional.of(variant));
        given(productVariantRepository.existsBySku("NEW-SKU")).willReturn(false);
        given(productVariantRepository.save(any(ProductVariant.class))).willAnswer(inv -> inv.getArgument(0));

        ProductVariant result = productService.updateVariant(1L, 10L, "NEW-SKU", "34",
                "Black", "#000000", null, null, null, null, null, null, null, null, null, null);

        assertThat(result.getSku()).isEqualTo("NEW-SKU");
        assertThat(result.getSizeLabel()).isEqualTo("34");
    }

    @Test
    void updateVariant_shouldThrowWhenSkuConflicts() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        ProductVariant variant = ProductVariant.create(product, "ORIGINAL-SKU", "32",
                null, null, null, null, null, null, null, null, null, null, null, null);
        given(productRepository.existsById(1L)).willReturn(true);
        given(productVariantRepository.findById(10L)).willReturn(Optional.of(variant));
        given(productVariantRepository.existsBySku("TAKEN-SKU")).willReturn(true);

        assertThatThrownBy(() -> productService.updateVariant(1L, 10L, "TAKEN-SKU", "32",
                null, null, null, null, null, null, null, null, null, null, null, null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));
    }

    @Test
    void deleteVariant_shouldRemoveVariant() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        ProductVariant variant = ProductVariant.create(product, "SKU-1", "M",
                null, null, null, null, null, null, null, null, null, null, null, null);
        given(productRepository.existsById(1L)).willReturn(true);
        given(productVariantRepository.findById(10L)).willReturn(Optional.of(variant));

        productService.deleteVariant(1L, 10L);

        verify(productVariantRepository).delete(variant);
    }

    @Test
    void addTranslation_shouldSaveTranslation() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productTranslationRepository.existsByProductIdAndLocale(anyLong(), eq("en"))).willReturn(false);
        given(productTranslationRepository.save(any(ProductTranslation.class))).willAnswer(inv -> inv.getArgument(0));

        ProductTranslation result = productService.addTranslation(1L, "en", "21oz Selvedge", "Heavy denim");

        assertThat(result.getLocale()).isEqualTo("en");
        assertThat(result.getName()).isEqualTo("21oz Selvedge");
    }

    @Test
    void addTranslation_shouldThrowWhenLocaleAlreadyExists() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productTranslationRepository.existsByProductIdAndLocale(anyLong(), eq("en"))).willReturn(true);

        assertThatThrownBy(() -> productService.addTranslation(1L, "en", "Name", null))
                .isInstanceOf(BusinessException.class)
                .satisfies(ex -> assertThat(((BusinessException) ex).getErrorCode())
                        .isEqualTo(ErrorCode.DUPLICATE_ENTITY));

        verify(productTranslationRepository, never()).save(any());
    }

    @Test
    void addImage_shouldSaveImage() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productImageRepository.save(any(ProductImage.class))).willAnswer(inv -> inv.getArgument(0));

        ProductImage result = productService.addImage(1L, "https://example.com/img.jpg", (short) 0, false);

        assertThat(result.getUrl()).isEqualTo("https://example.com/img.jpg");
        verify(productImageRepository, never()).clearPrimaryByProductId(anyLong());
    }

    @Test
    void addImage_shouldClearPreviousPrimaryWhenNewIsPrimary() {
        Brand brand = createBrand();
        Product product = createProduct(brand);
        given(productRepository.findById(1L)).willReturn(Optional.of(product));
        given(productImageRepository.save(any(ProductImage.class))).willAnswer(inv -> inv.getArgument(0));

        productService.addImage(1L, "https://example.com/img.jpg", (short) 0, true);

        verify(productImageRepository).clearPrimaryByProductId(anyLong());
    }

    @Test
    void deleteImage_shouldRemoveImage() {
        ProductImage image = ProductImage.create(null, "https://example.com/img.jpg", (short) 0, false);
        given(productRepository.existsById(1L)).willReturn(true);
        given(productImageRepository.findById(10L)).willReturn(Optional.of(image));

        productService.deleteImage(1L, 10L);

        verify(productImageRepository).delete(image);
    }
}
