services:
  mysql:
    image: mysql:8.0
    container_name: ev-mysql
    ports: ["3307:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: sa
      MYSQL_PASSWORD: "1234"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 5s
      retries: 8

  kafka1: &kafka
    image: apache/kafka:3.8.1
    container_name: ev-kafka1
    ports: ["19092:19092"]
    environment: &kafka-env
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@ev-kafka1:9093,2@ev-kafka2:9093,3@ev-kafka3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ev-kafka1:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  kafka2:
    <<: *kafka
    container_name: ev-kafka2
    ports: ["19093:19093"]
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ev-kafka2:9092,EXTERNAL://localhost:19093

  kafka3:
    <<: *kafka
    container_name: ev-kafka3
    ports: ["19094:19094"]
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:19094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ev-kafka3:9092,EXTERNAL://localhost:19094

  redis:
    image: redis:7-alpine
    container_name: ev-redis
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
