apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
spec:
  template:
    spec:
      containers:
        - name: service-product
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75"
