apiVersion: v1
kind: Service
metadata:
  name: service-product
  namespace: ecommerce
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: service-product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-product
  template:
    metadata:
      labels:
        app: service-product
    spec:
      containers:
        - name: service-product
          image: ecommerce/service-product:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: DB_NAME
              value: "ecommerce_product"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
