apiVersion: v1
kind: Service
metadata:
  name: service-customer
  namespace: ecommerce
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: service-customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-customer
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-customer
  template:
    metadata:
      labels:
        app: service-customer
    spec:
      containers:
        - name: service-customer
          image: ecommerce/service-customer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: DB_NAME
              value: "ecommerce_customer"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
