apiVersion: v1
kind: Service
metadata:
  name: service-order
  namespace: ecommerce
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: service-order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-order
  template:
    metadata:
      labels:
        app: service-order
    spec:
      containers:
        - name: service-order
          image: ecommerce/service-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: DB_NAME
              value: "ecommerce_order"
            - name: PRODUCT_SERVICE_URL
              value: "http://service-product:8081"
            - name: CUSTOMER_SERVICE_URL
              value: "http://service-customer:8084"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
