apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-payment
  namespace: ecommerce
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-payment
  serviceName: mysql-payment-service
  template:
    metadata:
      labels:
        app: mysql-payment
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_ROOT_PASSWORD
              name: ecommerce-secrets
        image: mysql:8.0
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 700m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /docker-entrypoint-initdb.d
          name: init
      nodeSelector:
        role: db
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-payment-init
        name: init
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 3Gi
      volumeMode: Filesystem
---
apiVersion: v1
data:
  01-init.sql: 'CREATE DATABASE IF NOT EXISTS ecommerce_payment CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

    CREATE USER IF NOT EXISTS ''sa''@''%'' IDENTIFIED BY ''changeme'';

    GRANT ALL PRIVILEGES ON ecommerce_payment.* TO ''sa''@''%'';

    FLUSH PRIVILEGES;

    '
kind: ConfigMap
metadata:
  name: mysql-payment-init
  namespace: ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-payment-service
  namespace: ecommerce
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-payment
  sessionAffinity: None
  type: ClusterIP
